project:
  # Use "book" instead of "website" to get a left sidebar of chapters
  type: book
  output-dir: docs

book:
  # Global title (appears at the top of the sidebar)
  title: "Python Math & ML Course"
  # author: "Metric Academy"
  repo-url: https://github.com/HaykTarkhanyan/python_math_ml_course
  repo-actions: [edit]
  # downloads: [pdf, epub]

  # Define chapters (top-level pages) and sub-chapters
  chapters:
    - index.qmd

    - part: "Math | Practical"
      chapters:
        - math\Resources\pr\pr01_vectors.qmd

    # - part: "Python"
    #   chapters:
    #     - python/Python_01_Intro.ipynb


    # - part: "ML"
    #   chapters:
    #     - ml/01_Regression_Main_Concepts/Code/C1_Regression_Main_Concepts.ipynb
    #     - ml/01_Regression_Main_Concepts/Code/C1_Hyperparameter_Optimization.ipynb

format:
  html:
    theme:
      light: cosmo   # light mode theme
      dark: darkly   # dark mode theme
    dark-mode-toggle: true
    dark-mode-toggle-position: right
    toc: true
    toc-location: right
    number-sections: true
    number-sections-by-file: true

    # Use lowercase for boolean settings
    code-fold: false

    highlight-style: github

execute:
  enabled: false
  freeze: auto
