project:
  type: book
  output-dir: _book

book:
  title: "Python Math & ML Course"
  repo-url: "https://github.com/HaykTarkhanyan/python_math_ml_course"
  repo-actions: [edit]
  # downloads: [pdf]
  chapters:
    - index.qmd
    - part: Python
      chapters: 
        - file: python/01_P_L01_Print_comments_variables_numbers_input.ipynb

    - part: "Math | Practicals"
      chapters:
        - file: "math/Resources/Practicals/pr_01_Vectors/pr01_vectors.qmd"
        - file: "math/Resources/Practicals/pr_02_Matrices/pr02_matrices.qmd"

format:
  html:
    theme:
      light: cosmo   # light mode theme
      dark: darkly   # dark mode theme
    dark-mode-toggle: true
    dark-mode-toggle-position: right
    toc: true
    toc-location: right
    number-sections: true
    number-sections-by-file: true

    # Use lowercase for boolean settings
    code-fold: false

    highlight-style: github

execute:
  enabled: false
  freeze: auto
