project:
  type: book
  output-dir: docs

book:
  title: "Python Math & ML Course"
  repo-url: "https://github.com/HaykTarkhanyan/python_math_ml_course"
  repo-actions: [edit]
  # downloads: [pdf]
  # cover-image: "background_photos/py_09_sirt_sar_kuze.jpg"


  chapters:
    - index.qmd
    - part: Misc
      chapters:
      - file: misc/google_colab.qmd

    - part: Python
      chapters: 
        - file: python/01_intro.ipynb
        - file: python/02_conditions.ipynb
        - file: python/03_str_range_list_some_funcs.ipynb
        - file: python/04_loops.ipynb
        - file: python/05_lst_str_methods_one_line_if_for.ipynb
        - file: python/06_tuple_set_dictionary.ipynb
        - file: python/07_functions_1.ipynb
        - file: python/08_functions_2.ipynb
        - file: python/09_files_packages_terminal.ipynb
        - file: python/10_git_conda_pep8.ipynb
        - file: python/11_exception_handling.ipynb
        - file: python/12_streamlit_recursion.ipynb
        - file: python/13_decorators.ipynb
        - file: python/14_classes.ipynb
        - file: python/15_inheritance_polymorphism.ipynb  
        - file: python/16_encapsulation_abstraction.ipynb
        - file: python/17_dataclass_iterator_generator_context_manager.ipynb
        - file: python/18_youtube_translator.ipynb

    - part: Libraries
      chapters: 
        - file: python_libs/01_openai_api_timestamp_generator.ipynb
        - file: python_libs/02_numpy.ipynb
        - file: python_libs/03_pandas_1.ipynb
        - file: python_libs/04_pandas_2.ipynb
        - file: python_libs/05_data_viz.ipynb

    
    # - part: ML
    #   chapters: 
    #     - file: ml/Chapter 1 Regression Main Concepts/01_intro__lin_reg.qmd
    #     - file: ml/Chapter 1 Regression Main Concepts/Code/02_Regression_Main_Concepts.ipynb
   
   
format:
  html:
    theme:
      light: cosmo   # light mode theme
      dark: darkly   # dark mode theme
    dark-mode-toggle: true
    dark-mode-toggle-position: right
    
    toc: true
    toc-location: right

    number-sections: false
    number-sections-by-file: false

    # Use lowercase for boolean settings
    code-fold: false

    code-tools: true     # adds “Copy” & “Collapse” buttons
    code-overflow: wrap  # wraps long lines in code blocks
    highlight-style: github

execute:
  enabled: false
  freeze: auto

# comments:
#   hypothesis: true
# https://quarto.org/docs/output-formats/html-basics.html#commenting